In [1]:
import pandas as pd
import numpy as np

# Para que este código funcione:
- A pasta `EA-MD-QD-2026-02` deve estar no diretório `dados`
- Este ficheiro deve estar no mesmo nível do diretório `dados`
- Devem rodar duas vezes o ficheiro `routine_data.py` para salvarem a base de dados mensal e trismestral
- Criar o diretório `data_TR3` dentro do diretório `EA-MD-QD-2026-02`
- E, voilá!

In [2]:
dir = "dados/EA-MD-QD-2026-02/data_TR2"

dfM = pd.read_excel(f"{dir}/PTdataM_NA__TR2.xlsx")
dfQ = pd.read_excel(f"{dir}/PTdataQ_NA__TR2.xlsx")

dfA = pd.read_excel("dados/EA-MD-QD-2026-02/raw/PTdata.xlsx")

In [3]:
dfM.head()

,Date,UNETOT_PT,UNEO25_PT,UNEU25_PT,REER42_PT,LTIRT_PT,IPMN_PT,IPCAG_PT,IPCOG_PT,IPDCOG_PT,...,HICPNG_PT,ICONFIX_PT,CCONFIX_PT,ESENTIX_PT,KCONFIX_PT,RTCONFIX_PT,SCONFIX_PT,BCI_PT,CCI_PT,SHIX_PT
0,2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dfA.head()

,Time,GDP_PT,EXPGS_PT,IMPGS_PT,GFCE_PT,HFCE_PT,CONSD_PT,GCF_PT,GFCF_PT,GFACON_PT,...,DFGDP_PT,ICONFIX_PT,CCONFIX_PT,ESENTIX_PT,KCONFIX_PT,RTCONFIX_PT,SCONFIX_PT,BCI_PT,CCI_PT,SHIX_PT
0,2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.3,-2.4,113.9,-15.8,9.4,10.3,102.2262,102.3880,110.4053
1,2000-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.9,-3.0,116.7,-5.6,11.0,14.2,102.5146,102.2470,124.9385
2,2000-03-01,43450.6,10151.5,13257.6,7387.6,28123.5,3524.1,10981.3,11097.5,7270.5,...,72.43,7.7,-3.2,116.2,-0.1,11.7,11.9,102.6476,101.9521,128.3406
3,2000-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.8,-9.2,114.1,-13.5,6.1,13.2,102.7988,101.5175,115.6546
4,2000-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.1,-8.0,113.3,-3.7,1.5,6.0,102.8972,101.2843,112.0247

In [8]:
dfMonthly = dfA[['Time',] + dfM.drop('Date', axis=1).columns.tolist()].copy()
dfMonthly.head()

,Time,UNETOT_PT,UNEO25_PT,UNEU25_PT,REER42_PT,LTIRT_PT,IPMN_PT,IPCAG_PT,IPCOG_PT,IPDCOG_PT,...,HICPNG_PT,ICONFIX_PT,CCONFIX_PT,ESENTIX_PT,KCONFIX_PT,RTCONFIX_PT,SCONFIX_PT,BCI_PT,CCI_PT,SHIX_PT
0,2000-01-01,5.6,4.4,12.7,96.14621,5.81,123.5,191.3,118.0,129.6,...,42.419421,7.3,-2.4,113.9,-15.8,9.4,10.3,102.2262,102.3880,110.4053
1,2000-02-01,5.4,4.1,13.0,95.12462,5.78,122.7,177.4,119.8,131.1,...,42.538342,8.9,-3.0,116.7,-5.6,11.0,14.2,102.5146,102.2470,124.9385
2,2000-03-01,5.3,4.0,12.4,94.49293,5.61,116.5,164.6,116.5,124.8,...,42.544582,7.7,-3.2,116.2,-0.1,11.7,11.9,102.6476,101.9521,128.3406
3,2000-04-01,5.2,3.9,12.8,94.90064,5.52,115.5,159.3,118.0,125.3,...,44.157190,8.8,-9.2,114.1,-13.5,6.1,13.2,102.7988,101.5175,115.6546
4,2000-05-01,5.3,4.0,13.1,94.96760,5.68,120.8,171.0,121.0,127.9,...,43.969543,10.1,-8.0,113.3,-3.7,1.5,6.0,102.8972,101.2843,112.0247

In [9]:
dfQuarter = dfA[['Time',] + dfQ.drop('Date', axis=1).columns.tolist()].copy()
dfQuarter.head()

,Time,GDP_PT,EXPGS_PT,IMPGS_PT,GFCE_PT,HFCE_PT,CONSD_PT,GCF_PT,GFCF_PT,GFACON_PT,...,HHLB.LLN_PT,ULCIN_PT,ULCMQ_PT,ULCMN_PT,ULCCON_PT,ULCRT_PT,ULCFC_PT,ULCRE_PT,ULCPR_PT,DFGDP_PT
0,2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-03-01,43450.6,10151.5,13257.6,7387.6,28123.5,3524.1,10981.3,11097.5,7270.5,...,59309.7,64.8,NaN,NaN,NaN,72.2,NaN,NaN,NaN,72.43
3,2000-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
dfMonthly.to_excel("dados/EA-MD-QD-2026-02/data_TR3/monthly-PT.xlsx", index=False)
dfQuarter.to_excel("dados/EA-MD-QD-2026-02/data_TR3/quarter-PT.xlsx", index=False)